plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
env:
  node: true
  es6: true
parser: babel-eslint
rules:
  import/no-commonjs: off
  prettier/prettier: error
  no-unused-vars:
    - error
    -
      vars: local
      args: none
      ignoreRestSiblings: true
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: true
        FunctionExpression: true
  valid-jsdoc:
    - error
    - prefer:
        return: "returns"
settings:
  import/resolver: node