name: 'resource'
database:
  production:
    driver: 'memory'
    database: 'test_api'
    autoReconnect: true
  development:
    driver: 'memory'
    database: 'test_api'
    autoReconnect: true
  test:
    driver: 'memory'
    database: 'test_api'
    autoReconnect: true
cors:
  enabled: true
  origin: "http://localhost:3000"
  headers:
    - Content-Type
  methods:
    - PUT
    - POST