platform: web
server:
  cors:
    from: mydomain.com

  parsers:
    json: true
    urlEncoded: true

  helmet: true

  logging:
    meta: true
    colorize: true
    transports:
      general:
        type: Console
        level: info
        json: true
        colorize: true

modules:
  - modules/compression
  - modules/cors
  - modules/body-parser
  - modules/logger
  - __mocks__/modules/moduleOne
  - __mocks__/modules/moduleTwo